name: icegen

services:
  log-generator-otel:
    build:
      context: .
    env_file:
      - .env
    command: ["otel", "--endpoint", "${OTEL_LOGS_ENDPOINT}"]
    profiles: ["otel"]
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 512M
    extra_hosts:
      - "host.docker.internal:host-gateway"
